/* prettier-ignore */
/* eslint-disable */
// Generated by elegant-router
// Read more: https://github.com/mufeng889/elegant-router
// Vue auto route: https://github.com/soybeanjs/elegant-router
// 请不要手动修改此文件，否则会导致优雅路由无法正常工作
// 如果需要修改，请在优雅路由配置文件中进行修改
// 这是自动生成的文件，请不要手动修改

import type { RouteKey, RouteMap, RoutePath } from '@soybean-react/vite-plugin-react-router';

/**
 * map of route name and route path
 */
export const routeMap: RouteMap = {
  "not-found": "*",
  root: "/",
  admin: "/admin",
  "admin_(base)_home": "/admin/home",
  douyin: "/douyin",
  douyin_home: "/douyin/home",
};

/**
 * get route path by route name
 *
 * @param name route name
 */
export function getRoutePath<T extends RouteKey>(name: T) {
  return routeMap[name];
}

/**
 * get route name by route path
 *
 * @param path route path
 */
export function getRouteName(path: RoutePath) {
  const routeEntries = Object.entries(routeMap) as [RouteKey, RoutePath][];

  const routeName: RouteKey | null =
    routeEntries.find(([, routePath]) => routePath === path)?.[0] || null;

  return routeName;
}
