/* prettier-ignore */
/* eslint-disable */
// Generated by elegant-router
// Read more: https://github.com/mufeng889/elegant-router
// Vue auto route: https://github.com/soybeanjs/elegant-router
// 请不要手动修改此文件，否则会导致优雅路由无法正常工作
// 如果需要修改，请在优雅路由配置文件中进行修改
// 这是自动生成的文件，请不要手动修改

//这里只能修改 handle 并且路由组作为布局路由组件 是不能有handle的

import type { ElegantConstRoute } from '@soybean-react/vite-plugin-react-router';

export const generatedRoutes: ElegantConstRoute[] = [
  {
    matchedFiles: ['admin', '/src/pages/admin/index.tsx', '/src/pages/admin/loading.tsx', null],
    name: 'admin',
    path: '/admin',
    handle: {},
    children: [
      {
        matchedFiles: ['admin_(base)', null, null, null],
        name: 'admin_(base)',
        children: [
          {
            matchedFiles: [null, '/src/pages/admin/(base)/about/index.tsx', null, null],
            name: 'admin_(base)_about',
            path: '/admin/about',
            handle: { i18nKey: 'route.admin_(base)_about', title: '(base)_about' }
          },
          {
            matchedFiles: [null, '/src/pages/admin/(base)/function/index.tsx', null, null],
            name: 'admin_(base)_function',
            path: '/admin/function',
            handle: { i18nKey: 'route.admin_(base)_function', title: '(base)_function' }
          },
          {
            matchedFiles: [null, '/src/pages/admin/(base)/home/index.tsx', null, null],
            name: 'admin_(base)_home',
            path: '/admin/home',
            handle: { i18nKey: 'route.admin_(base)_home', title: '(base)_home' }
          },
          {
            matchedFiles: [null, '/src/pages/admin/(base)/user-center/index.tsx', null, null],
            name: 'admin_(base)_user-center',
            path: '/admin/user-center',
            handle: { i18nKey: 'route.admin_(base)_user-center', title: '(base)_user-center' }
          }
        ],
        path: null
      }
    ]
  },
  {
    matchedFiles: [null, null, null, null],
    name: 'douyin',
    path: '/douyin',
    handle: {},
    children: [
      {
        matchedFiles: [null, '/src/pages/douyin/home/index.tsx', null, null],
        name: 'douyin_home',
        path: '/douyin/home',
        handle: {}
      }
    ]
  },
  { matchedFiles: [null, '404', null, null], name: 'notFound', path: '*', handle: {} }
];
